{lib, config, pkgs, ...}:

{
    
    system.stateVersion = "24.11";

    nixpkgs.config.allowUnfree = true;
    environment.systemPackages = with pkgs; [];

    nix.settings.experimental-features = [ "nix-command" "flakes" ];

    environment.variables.EDITOR = "nvim";
    
    # Fcitx5-Rime Input Method
    i18n.inputMethod = {
        enable = true;
        type = "fcitx5";
        fcitx5 = {
            addons = with pkgs; [
	           rime-data
                fcitx5-gtk
                fcitx5-rime
	           librime
	           librime-lua
            ];    
            waylandFrontend = true;
        };  
    };
    
    # Login Manager
    services.greetd = {
          enable = true;
          settings = {
            default_session = {
              # Wayland Desktop Manager is installed only for user ryan via home-manager!
              user = "y5htola";
              # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
              # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
              command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
            };
        };
    };
 
    
    # Virtualization
    virtualisation.libvirtd.enable = true;
    programs.virt-manager.enable = true;
    
    # clash-verge
    programs.clash-verge = {
        package = pkgs.clash-verge-rev;
        enable = true;
        tunMode = true;
    };
    
    # Hyprland
    #programs.hyprland = {
    #    enable = true;
    #    xwayland.enable = true;
    #};
}
